"""
Tests for Story 1.1: Initialize Python Project with Astral uv

Verifies all acceptance criteria:
AC1: All required dependencies are installed and importable
AC2: pyproject.toml exists with Python 3.10+ specified
AC3: Playwright Chromium is installed (checked via import)
"""

import importlib
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).parent.parent
REQUIRED_PACKAGES = [
    "httpx",
    "trafilatura",
    "playwright",
    "langchain",
    "langchain_chroma",
    "langchain_ollama",
    "streamlit",
    "rich",
    "yaml",  # pyyaml
]


class TestDependenciesInstalled:
    """AC1: All dependencies must be importable after uv sync."""

    def test_httpx_importable(self):
        assert importlib.util.find_spec("httpx") is not None, "httpx not installed"

    def test_trafilatura_importable(self):
        assert importlib.util.find_spec("trafilatura") is not None, "trafilatura not installed"

    def test_playwright_importable(self):
        assert importlib.util.find_spec("playwright") is not None, "playwright not installed"

    def test_langchain_importable(self):
        assert importlib.util.find_spec("langchain") is not None, "langchain not installed"

    def test_langchain_chroma_importable(self):
        assert importlib.util.find_spec("langchain_chroma") is not None, "langchain-chroma not installed"

    def test_langchain_ollama_importable(self):
        assert importlib.util.find_spec("langchain_ollama") is not None, "langchain-ollama not installed"

    def test_streamlit_importable(self):
        assert importlib.util.find_spec("streamlit") is not None, "streamlit not installed"

    def test_rich_importable(self):
        assert importlib.util.find_spec("rich") is not None, "rich not installed"

    def test_pyyaml_importable(self):
        assert importlib.util.find_spec("yaml") is not None, "pyyaml not installed"


class TestPyprojectToml:
    """AC2: pyproject.toml must exist with Python 3.10+ requirement."""

    def test_pyproject_toml_exists(self):
        pyproject = PROJECT_ROOT / "pyproject.toml"
        assert pyproject.exists(), "pyproject.toml not found at project root"

    def test_pyproject_requires_python_310_or_higher(self):
        import tomllib

        pyproject = PROJECT_ROOT / "pyproject.toml"
        with open(pyproject, "rb") as f:
            data = tomllib.load(f)
        requires = data["project"].get("requires-python", "")
        assert requires, "requires-python not set in pyproject.toml"
        # Accept >=3.10, >=3.11, >=3.12, >=3.13, >=3.14, etc.
        import re
        match = re.search(r">=3\.(\d+)", requires)
        assert match, f"requires-python '{requires}' doesn't match >=3.X pattern"
        minor = int(match.group(1))
        assert minor >= 10, f"requires-python specifies 3.{minor}, need 3.10+"

    def test_pyproject_has_all_required_deps(self):
        import tomllib

        pyproject = PROJECT_ROOT / "pyproject.toml"
        with open(pyproject, "rb") as f:
            data = tomllib.load(f)
        deps = [d.lower() for d in data["project"].get("dependencies", [])]
        required = ["httpx", "trafilatura", "playwright", "langchain", "langchain-chroma",
                    "langchain-ollama", "streamlit", "rich"]
        for req in required:
            assert any(req in dep for dep in deps), f"Dependency '{req}' missing from pyproject.toml"


class TestUvLockFile:
    """Verify uv.lock exists (generated by uv sync, confirming lock file is maintained)."""

    def test_uv_lock_exists(self):
        lock_file = PROJECT_ROOT / "uv.lock"
        assert lock_file.exists(), "uv.lock not found — run 'uv sync' to generate it"


class TestPlaywrightChromium:
    """AC3: Playwright Chromium must be importable post-install."""

    def test_playwright_async_api_importable(self):
        """Core playwright async API must import cleanly."""
        import playwright.async_api  # noqa: F401
        assert True, "playwright.async_api imported successfully"
